### PR TITLE
[#496] Run Stan on Summoner and fix observations

### LINKED ISSUE #496: Run Stan on Summoner and fix observations
As we added `hie` files generation option, we can try this 😼

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #496

There were 30 observations, now down to 2 (`length` ones which are not resolvable now).
The code was actually pretty good already 👍🏼

### CODE REVIEW

File: summoner-cli/src/Summoner/GhcVer.hs [hunk 1]
```diff
@@ -106,12 +105,13 @@ baseVer = show . baseVerPvp
 
 -}
 cabalBaseVersions :: [GhcVer] -> Text
-cabalBaseVersions []   = ""
-cabalBaseVersions [v]  = "^>= " <> baseVer v
-cabalBaseVersions ghcs = ">= " <> baseVer (minimum ghcs) <> " && < " <> upperBound
+cabalBaseVersions ghcVers = case sort ghcVers of
+    [] -> ""
+    [v] -> "^>= " <> baseVer v
+    (minGhc:rest) -> ">= " <> baseVer minGhc <> " && < " <> upperBound (minGhc :| rest)
```
Comment (chshersh) [inline summoner-cli/src/Summoner/GhcVer.hs:111]: This list will have at least two elements, so we can go even further a bit:
```suggestion
    minGhc:x:xs -> ">= " <> baseVer minGhc <> " && < " <> upperBound (x :| xs)
```

File: summoner-cli/src/Summoner/GhcVer.hs [hunk 2]
```diff
@@ -106,12 +105,13 @@ baseVer = show . baseVerPvp
...
   where
-    upperBound :: Text
-    upperBound = let Pvp{..} = baseVerPvp $ maximum ghcs in
+    upperBound :: NonEmpty GhcVer -> Text
+    upperBound ghcs = let Pvp{..} = baseVerPvp $ last ghcs in
         show pvpFirst <> "." <> show (pvpSecond + 1)
```
Comment (chshersh) [inline summoner-cli/src/Summoner/GhcVer.hs:115]: Very nice refactoring! No partial functions in the end :sunglasses:

File: summoner-cli/test/Test/TomlSpec.hs [hunk 3]
```diff
@@ -36,9 +36,6 @@ tomlConfigSpec = describe "TOML configuration spec" $ do
     it "default configuration is up-to-date" $
         readFileText "examples/summoner-default.toml"
             `shouldReturn` defaultConfigFileContent
-  where
-    isSuccess :: Validation e a -> Bool
-    isSuccess = \case { Success _ -> True; _ -> False }
```
Comment (chshersh) [inline summoner-cli/test/Test/TomlSpec.hs:41]: Nice!

File: summoner-tui/src/Summoner/Tui/Validation.hs [hunk 4]
```diff
@@ -231,9 +230,9 @@ formErrorMessages :: [FilePath] -> KitForm e -> [String]
 formErrorMessages dirs kitForm = validatedErrorMessages ++ ghcErrorMessage
   where
     validatedErrorMessages :: [String]
-    validatedErrorMessages = case validateKit dirs (formState kitForm) of
-        Success _      -> []
-        Failure errors -> map showFormError $ toList errors
+    validatedErrorMessages = whenFailure []
+        (validateKit dirs $ formState kitForm)
+        (map showFormError . toList)
```
Comment (chshersh) [inline summoner-tui/src/Summoner/Tui/Validation.hs:235]: Turns out, we implemented useful functions in `validation`!
