### PR TITLE
[#178] Remove trailing spaces, newlines

### LINKED ISSUE #168: wrong version of cabal for Travis CI (specific prelude) ?
Hello

I created a projet using this configuration file:

```
cabal    = false
stack    = true
owner    = "pascalpoizat"
fullName = "Pascal Poizat"
email    = "pascal.poizat@gmail.com"
license  = "Apache-2.0"
ghcVers  = ["8.4.3"]
github   = true
travis   = true
appveyor = true
private  = false
lib      = true
exe      = true
test     = true
bench    = true

extensions = [ "DeriveGeneric"
             , "GeneralizedNewtypeDeriving"
             , "LambdaCase"
             , "OverloadedStrings"
             , "RecordWildCards"
             , "ScopedTypeVariables"
             , "TypeApplications"
             , "NoImplicitPrelude"
             ]

warnings = [ "-fwarn-unused-imports"
           , "-fwarn-incomplete-uni-patterns"
           , "-fwarn-incomplete-patterns"
           , "-fwarn-overlapping-patterns"
           , "-fwarn-missing-signatures"
           , "-fwarn-name-shadowing"
           ]

[prelude]
    package = "relude"
    module  = "Relude"
```

When travis runs I get this error:

```
--  While building custom Setup.hs for package base-noprelude-4.11.1.0 using:
      /home/travis/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.4.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.0.1.0 configure --with-ghc=/home/travis/.stack/programs/x86_64-linux/ghc-8.4.3/bin/ghc --with-ghc-pkg=/home/travis/.stack/programs/x86_64-linux/ghc-8.4.3/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/travis/.stack/snapshots/x86_64-linux/lts-12.12/8.4.3/pkgdb --package-db=/home/travis/build/pascalpoizat/fbpmn/.stack-work/install/x86_64-linux/lts-12.12/8.4.3/pkgdb --libdir=/home/travis/build/pascalpoizat/fbpmn/.stack-work/install/x86_64-linux/lts-12.12/8.4.3/lib --bindir=/home/travis/build/pascalpoizat/fbpmn/.stack-work/install/x86_64-linux/lts-12.12/8.4.3/bin --datadir=/home/travis/build/pascalpoizat/fbpmn/.stack-work/install/x86_64-linux/lts-12.12/8.4.3/share --libexecdir=/home/travis/build/pascalpoizat/fbpmn/.stack-work/install/x86_64-linux/lts-12.12/8.4.3/libexec --sysconfdir=/home/travis/build/pascalpoizat/fbpmn/.stack-work/install/x86_64-linux/lts-12.12/8.4.3/etc --docdir=/home/travis/build/pascalpoizat/fbpmn/.stack-work/install/x86_64-linux/lts-12.12/8.4.3/doc/base-noprelude-4.11.1.0 --htmldir=/home/travis/build/pascalpoizat/fbpmn/.stack-work/install/x86_64-linux/lts-12.12/8.4.3/doc/base-noprelude-4.11.1.0 --haddockdir=/home/travis/build/pascalpoizat/fbpmn/.stack-work/install/x86_64-linux/lts-12.12/8.4.3/doc/base-noprelude-4.11.1.0 --dependency=base=base-4.11.1.0
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/travis/build/pascalpoizat/fbpmn/.stack-work/logs/base-noprelude-4.11.1.0.log
    Configuring base-noprelude-4.11.1.0...
    Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.4.3: This package description follows
    version 2.2 of the Cabal specification. This tool only supports up to version
    2.0.1.0.
The command "stack build --only-dependencies --no-terminal" failed and exited with 1 during .
```

I was able to solve the issue replacing:

```
  - stack setup --no-terminal --install-cabal 2.0.1.0
```

by:

```
  - stack setup --no-terminal --install-cabal 2.2.0.1
```

### LINKED ISSUE #178: Remove unnecessary `endLine`s at the end of the generated files
We have this mysterious `endLine` at the end of the most QQ in Template module. If previously in `hs-init` it made sense (we were putting all into one big `stack.template` file) but now it just leftovers from the past.

I suggest to remove them from most of the places. For the tricky files like `.cabal` we need to do it in another way. Instead of adding the new line at the end of all parts of this file we will put the newline at the beginning of the added sections.

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #178
Also resolves #168 

## Checklist:

- [x] I've updated the [CHANGELOG](https://github.com/kowainik/summoner/blob/master/CHANGELOG.md) with the short description of my latest changes.
- [x] All new and existing tests pass.
- [x] I keep the code style used in the files I've changed (see [style-guide](https://github.com/kowainik/org/blob/master/style-guide.md#haskell-style-guide) for more details).
- [x] I've used the [`stylish-haskell` file](https://github.com/kowainik/summoner/blob/master/.stylish-haskell.yaml).
- [ ] My change requires the documentation updates.
  - [ ] I've updated the documentation accordingly.
- [x] I've added the `[ci skip]` text to the docs-only related commit's name.
- [x] I changed code related to the generated project.
  - [x] I created a new project using `summoner` and I checked that this specific feature is working as expected.

### CODE REVIEW

File: src/Summoner/Template/GitHub.hs [hunk 1]
```diff
@@ -118,23 +99,35 @@ gitHubFiles Settings{..} =
...
+        - "$$TRAVIS_BUILD_DIR/.stack-work"
+        |]
+
+
     cabalTest :: Text
     cabalTest = if settingsTest then "cabal new-test" else "echo 'No tests'"
 
+    travisCabalMtr :: Text
+    travisCabalMtr = memptyIfFalse settingsCabal $
+        T.concat $ map travisCabalMatrixItem settingsTestedVersions
```
Comment (ChShersh) [inline src/Summoner/Template/GitHub.hs]: What do you think about having the following function:

```haskell
tconcatMap :: (a -> Text) -> [a] -> Text
tconcatMap f = T.concat . map f
```

Not necessary in this PR (I can create simple and small refactoring issue for that) but I see that we use such pattern a lot, so probably can add this in `Summoner.Text` module and replace all occurrences of this.

File: CHANGELOG.md [hunk 2]
```diff
@@ -6,11 +6,16 @@
 * [#169](https://github.com/kowainik/summoner/issues/169):
   Make AppVeyor use the 64bits version of stack and build for 64 bits.
 * [#154](https://github.com/kowainik/summoner/issues/154):
-* Add `Link` constructor to `Source` data type.
+  Add `Link` constructor to `Source` data type.
```
Comment (ChShersh) [inline CHANGELOG.md]: Thanks for fixing the typo!

File: src/Summoner/Template/Cabal.hs [hunk 3]
```diff
@@ -18,7 +18,7 @@ cabalFile :: Settings -> TreeFs
 cabalFile Settings{..} = File (toString settingsRepo ++ ".cabal") cabalFileContent
   where
     cabalFileContent :: Text
-    cabalFileContent = mconcat
+    cabalFileContent = T.concat
```
Comment (ChShersh) [inline src/Summoner/Template/Cabal.hs]: Great :+1:

File: src/Summoner/Template/Stack.hs [hunk 4]
```diff
@@ -16,31 +16,24 @@ stackFiles Settings{..} = map createStackYaml settingsTestedVersions
...
+    createStackYaml ghcV = File (toString $ "stack" <> ver <> ".yaml")
+        $ "resolver: lts-" <> latestLts ghcV <> extraDeps <> ghcOpts
       where
-        stackYaml :: Text -> Text -> Text -> TreeFs
-        stackYaml ghc lts baseV = File (toString $ "stack" <> ghc <> ".yaml")
-            [text|
-            resolver: lts-${lts}
+        ver :: Text
+        ver = case ghcV of
+            Ghc843 -> ""
```
Comment (ChShersh) [inline src/Summoner/Template/Stack.hs]: At one hand I feel that in order to be more resilent to refactoring this should be something like `if ghcV == defaultGHC then ...` but on the other hand it might complicate support of default ghc for `stack` and `cabal` when the default is different (like now: `stack` default is GHC-8.4.3 and cabal could have GHC 8.6.1)
